version: '2'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile_development
    command: bundle exec unicorn -p 3000 -c config/unicorn.rb
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/workdir
      - /var/tmp
      #ソケット通信用ファイルをnginxコンテナと共有
      - sockets:/workdir/tmp/sockets
    tty: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    extends:
      file: ./docker/mysql/password.yml
      service: password

  db: 
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "4306:3306" # ホストからゲストへポートフォワード。sequelProと繋ぎたいので、3306ではなく4306をポートに指定
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql # データの永続化
    extends:  
      file: ./docker/mysql/password.yml
      service: password

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - sockets:/workdir/tmp/sockets
    depends_on:
      - app

volumes:
  sockets:
  mysql-data: