version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile_development
    # 一度サーバーが起動すると起動し続けるので、rm -f /workdir/tmp/pids/server.pidで、dockerが起動する度に一旦停止させる
    command: /bin/sh -c "rm -f /workdir/tmp/pids/server.pid && bundle exec unicorn -p 3000 -c /workdir/config/unicorn.rb"
    tty: true #pry-byebugを使えるようにする"
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    extends:
      file: ./docker/mysql/password.yml
      service: password
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/workdir # ソースコード変更したらDocker側も即反映されるように
      #ソケット通信用ファイルをnginxコンテナと共有
      - tmp-data:/workdir/tmp/sockets
      #画像データとかをnginxと共有
      - public-data:/workdir/public

  db: 
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql # データの永続化
    ports:
      - "4306:3306" # ホストからゲストへポートフォワード。sequelProと繋ぎたいので、3306ではなく4306をポートに指定
    extends:  
      file: ./docker/mysql/password.yml
      service: password

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/workdir/tmp/sockets
      - public-data:/workdir/public
    depends_on:
      - web 

volumes:
  public-data:
  tmp-data:
  mysql-data: