version: '2'
services:

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    extends:  
      file: ./docker/mysql/password.yml
      service: password
    ports:
      - "4306:3306"

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile_development
    environment:
      RAILS_ENV:  development #切替必要test
    command: bundle exec unicorn -p 3000 -c config/unicorn.rb
    env_file: .env #切替必要
    ports:
      - "3000:3000"
    volumes:
      - .:/workdir
      - /var/tmp
    tty: true
    depends_on:
      - db
    links:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - app
    depends_on:
      - app
    volumes_from:
      - app

volumes:
  mysql-data: