FROM ruby:2.6.5
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    default-mysql-client \
    nodejs \
    npm \
    vim \
    sudo && \
    npm install -g -y yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /workdir
WORKDIR /workdir
COPY Gemfile .
COPY Gemfile.lock .

RUN gem install bundler -v 2.1.4
RUN bundle install && \
    bundle exec rails webpacker:install
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    echo "Asia/Tokyo" > /etc/timezone

COPY . .

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

RUN rails assets:precompile && \
    yarn cache clean && \
    rm -rf node_modules tmp/cache
ENV RAILS_SERVE_STATIC_FILES="true"
CMD ["bundle", "exec", "unicorn", "-c", "config/unicorn.rb"]