FROM ruby:2.6.5
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    default-mysql-client \
    nodejs \
    npm \
    vim \
    sudo && \
    npm install -g -y yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN rm -rf /var/www/workdir/* && mkdir -p /var/www/workdir
WORKDIR /workdir
ADD Gemfile /workdir/Gemfile
ADD Gemfile.lock /workdir/Gemfile.lock
RUN gem install bundler -v 2.1.4
RUN bundle install && \
    bundle exec rails webpacker:install
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    echo "Asia/Tokyo" > /etc/timezone
ADD /cat-28730 /workdir
RUN rails assets:precompile && \
    yarn cache clean && \
    rm -rf node_modules tmp/cache
ENV RAILS_SERVE_STATIC_FILES="true"
CMD ["bundle", "exec", "unicorn", "-e", "production", "-C", "config/unicorn.rb"]